site_name: python-by-examples
site_url: https://python-by-examples.readthedocs.io
repo_url: https://github.com/devops-by-examples/Python
strict: true
theme:
  name: material
  palette:
    primary: indigo
  font:
    text: 'Roboto'
  logo: 'assets/images/logo.png'
extra_css:
  - 'assets/extra.css'
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - About: index.md
  - Variables:
    - Introduction: variables/introduction.md
  - Operators:
    - Introduction: operators/introduction.md
    - Arithmetic: operators/arithmetic.md
    - Assignment: operators/assignment.md
    - Logical: operators/logical.md
    - Relational: operators/relational.md
    - Identity: operators/identity.md
    - Membership: operators/membership.md
    - Bitwise: operators/bitwise.md
    - Precedence: operators/precedence.md
  - Data Types:
    - Introduction: datatypes/introduction.md
    - Strings: 
      - Introduction: datatypes/strings/strings.md
    - List: 
      - Introduction: datatypes/list/list.md
      - Methods: datatypes/list/list_methods.md
      - Questions: datatypes/list/list_exercise.md
    - Tuple: 
      - Introduction: datatypes/tuple/tuple.md
      - Questions: datatypes/tuple/tuple_exercise.md
    - Set: 
      - Introduction: datatypes/set/set.md
      - Methods: datatypes/set/set_methods.md
      - Questions: datatypes/set/set_exercise.md
    - Dict: 
      - Introduction: datatypes/dict/dict.md
      - Methods: datatypes/dict/dict_methods.md
      - Questions: datatypes/dict/dict_exercise.md
  - Loops: 
    - Introduction: loops/introduction.md
    - While: loops/while.md
    - For: loops/for.md
    - Questions: loops/problems.md
